
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author suhai
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    JTextField name = new JTextField();
    JTextField pava = new JTextField();
    JFormattedTextField birthYear;
    String ranks[] = {"Avo","Beele","Crode","CrodeExalted"};
    JComboBox<String> rank = new JComboBox(ranks);

    public MainPanel() {
        try {
            birthYear = new JFormattedTextField(new MaskFormatter("####"));
            this.setLayout(new GridLayout(2,2));
            JLabel nameL = new JLabel("name : ");
            JLabel pavaL = new JLabel("pava :");
            JLabel birthYearL = new JLabel("birth year : ");
            JLabel rankL = new JLabel("rank : ");
            JPanel nameP = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            JPanel pavaP = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            JPanel birthYearP = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            JPanel rankP = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            nameP.add(nameL);
            nameP.add(name);
            pavaP.add(pavaL);
            pavaP.add(pava);
            birthYearP.add(birthYearL);
            birthYearP.add(birthYear);
            rankP.add(rankL);
            rankP.add(rank);
            this.add(nameP);
            this.add(pavaP);
            this.add(birthYearP);
            this.add(rankP);
            name.setColumns(20);
            pava.setColumns(20);
            birthYear.setColumns(20);
            name.setEnabled(false);
            pava.setEnabled(false);
            birthYear.setEnabled(false);
            rank.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
